// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Microservices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250814082407_AddDataElevatorfix")]
    partial class AddDataElevatorfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoorsModel", b =>
                {
                    b.Property<DateTime>("EventIdUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DoorId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("EventIdUtc");

                    b.ToTable("DataDoor");
                });

            modelBuilder.Entity("ElevatorModel", b =>
                {
                    b.Property<DateTime>("EventIdUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventIdUtc");

                    b.ToTable("DataElevator");
                });

            modelBuilder.Entity("SmokeDetectorModel", b =>
                {
                    b.Property<DateTime>("EventIdUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventIdUtc");

                    b.ToTable("DataSmokeDetector");
                });
#pragma warning restore 612, 618
        }
    }
}
